### ISSUE TITLE
Drop Python 2.7?

### ISSUE THREAD

**Issue by alexmojaki** [gristlabs/asttokens#111]
Continuing the discussion in https://github.com/gristlabs/asttokens/pull/110#issuecomment-1615147120

I've just noticed that GHA still has PyPy 2.7, which is actually probably enough to say that the library is still being tested on 2.7 and is thus expected to work. Dropping support (i.e. the PyPI classifier) is only valuable if it saves us from doing work to have that confidence.

On the other hand, I don't want people doing (or thinking that they have to do) extra work in the future for the sake of Python 2, e.g. I feel bad about the effort @palfrey went through with mypy and Python 2.

If we do go forward with this, https://github.com/gristlabs/asttokens/pull/67 would help.

**Comment by PeterJCLaw** [comment]
Cross linking: https://github.com/gristlabs/asttokens/issues/107

**Comment by aqeelat** [comment]
I just looked at Grist and their repo is setup with separate requirements.txt files for [python 2](https://github.com/gristlabs/grist-core/blob/main/sandbox/requirements.txt) and [python 3](https://github.com/gristlabs/grist-core/blob/main/sandbox/requirements3.txt). As long as we don't change the public api, I think we will be fine with removing python 2 support.

Since the projects are supposedly tied, the way I suggest we go about it is:
1. bump asttokens to version 3 and remove support for python 2
2. release critical bug fixes to version 2.2.x if needed
3. update [requirements.txt](https://github.com/gristlabs/grist-core/blob/main/sandbox/requirements.txt) to include `asttokens <=2.0.5,<3`
4. update [requirements3.txt](https://github.com/gristlabs/grist-core/blob/main/sandbox/requirements3.txt) to include the newer version 3

**Comment by aqeelat** [comment]
Also, new grit installations use python 3.9 by default, so we can also drop 3.5 and 3.6 since they're dead.

**Comment by dsagal** [comment]
Thank you all, @a-detiste, @alexmojaki, @aqeelat, for the great cleanup! Am I right that the next step is to update README (which currently claims that it works with Python 2) and bump asttokens to version 3?

**Comment by alexmojaki** [comment]
That sounds right to me.

**Comment by deronnax** [comment]
linking https://github.com/gristlabs/asttokens/pull/149 for reference. 
Could a release be done as soon as the README has been updated?

**Comment by dsagal** [comment]
FYI, asttokens v3.0.0 is now published. Closing. Thank you all!
