### ISSUE TITLE
Get node from token?

### ISSUE THREAD

**Issue by richtier** [gristlabs/asttokens#64]
Hello,

I have a line number and a column. I can use that to get the the token.

How can I get the node from the token?

currently I'm doing this, but perhaps there is a way built in to asttokens?

```py

def find_node_by_position(node, line, column):
    if isinstance(node, (nodes.ClassDef, nodes.FunctionDef)):
        node_line = node.fromlineno
    else:
        node_line = node.lineno

    node_column = node.col_offset

    if node_line == line and node_column == column:
        return node

    for child in node.get_children():
        result = find_node_by_position(child, line, column)
        if result:
            return result

    return None
```

**Comment by dsagal** [comment]
I think this is reasonable.

You could maybe simplify somewhat by using `ast.walk`. The `util` submodule in `asttokens` includes its own version of `walk`, that's probably more suitable because it makes some guarantees on ordering.

Also, once `ASTTokens` is constructed, all the nodes are annotated with `.first_token` and `.last_token` attributes. So if you have a token, you can use those attributes to compare nodes.

For efficiency, you can make a sorted list (like `sorted((n.first_token, n.last_token, n) for n in ast.walk(root))`), and then use `bisect` to find tokens in it quickly.

**Comment by richtier** [comment]
thanks
